server:
  port: 8083
spring:
  application:
    name: rating-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    url: jdbc:postgresql://localhost:5432/rating_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cloud:
    openfeign:
      client:
        config:
          rideFeignClient:
            url: http://ride-service:8084/rides
          default:
            connect-timeout: 5000
            readTimeout: 5000
            error-decoder: com.software.modsen.ratingservice.config.RideErrorDecoder
      circuitbreaker:
        enabled: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: rating-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: "*"
        kafka.consumer.trusted.packages: "*"
      bootstrap-servers: kafka:9092

eureka:
  instance:
    hostname: rating-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
